name: angulardart_github_search
description: A web app that uses AngularDart Components
version: 0.0.1
# homepage: https://www.example.com
publish_to: none

environment:
   sdk: ">=3.0.0 <4.0.0"

dependencies:
  ngdart: ^7.1.1
  angular_bloc: ^9.0.0
  bloc: ^8.1.0
  common_github_search:
    path: ../common_github_search

dev_dependencies:
  build_daemon: ^4.0.0
  build_runner: ^2.2.0
  build_web_compilers: ^3.2.6
